name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in web/src/pages/product
        run: |
          cd web/src/pages/product
          ls -al

      - name: Install dependencies
        run: |
          npm ci
        working-directory: ./web

      - name: Build project
        run: |
          npm run build
        env:
          REACT_APP_URL_API: ${{ vars.REACT_APP_URL_API }}
        working-directory: ./web

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CRUD_PRODUCT_REACT }}'
          channelId: live
          projectId: crud-product-react
          entryPoint: ./web
